# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        qt-version: [6.4]

    steps:
      - name: Prepare container for build
        run: |
          sudo apt-get build-dep
          sudo apt-get install libxcb-xinerama0-dev

      - name: Download Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest

      - name: Checkout Qt
        run: |
          git clone git://code.qt.io/qt/qt5.git
          cd qt5
          git checkout ${{ matrix.qt-version }}
          ./init-repository

      - name: Build host Qt
        run: |
          cd qt5
          mkdir build_host
          ../configure -opensource -confirm-license
          cmake --build .

      - name: Configure Qt
        run: |
          source emsdk/emsdk_env.sh
          pushd qt5
          mkdir build_wasm
          cd build_wasm
          ./configure -qt-host-path ../build_host \
            -xplatform wasm-emscripten \
            -nomake examples \
            -feature-thread \
            -opensource \
            -confirm-license
          cmake --build . -t qtbase -t qtsvg -t qtcharts
      
